import type { MetadataRoute } from "next";
import { kits, guides, tools } from "@/content/data";
import { siteUrl } from "@/lib/seo";

export const dynamic = "force-static";

/**
 * Sitemap for the v3 pages (deployed at the bitroot.org root). The blog has
 * its own sitemap at /blog/sitemap.xml (generated by blog/scripts/
 * build_index.py); robots.txt lists both.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes: { path: string; priority: number }[] = [
    { path: "/", priority: 1 },
    { path: "/about/", priority: 0.8 },
    { path: "/kits/", priority: 0.9 },
    { path: "/guides/", priority: 0.9 },
    { path: "/tools/", priority: 0.9 },
    { path: "/products/", priority: 0.8 },
    { path: "/community/", priority: 0.7 },
    { path: "/newsletter/", priority: 0.7 },
    { path: "/platter/", priority: 0.9 },
    { path: "/blog/", priority: 0.8 },
    { path: "/legal/privacy/", priority: 0.3 },
    { path: "/legal/terms/", priority: 0.3 },
    { path: "/legal/refund/", priority: 0.3 },
    { path: "/froots/privacy/", priority: 0.3 },
  ];

  const itemRoutes = [...kits, ...guides, ...tools].map((item) => ({
    url: `${siteUrl}/${item.category === "kit" ? "kits" : item.category === "guide" ? "guides" : "tools"}/${item.slug}/`,
    lastModified: item.updatedAt,
    priority: 0.7,
  }));

  return [
    ...staticRoutes.map(({ path, priority }) => ({
      url: `${siteUrl}${path}`,
      priority,
    })),
    ...itemRoutes,
  ];
}
