#!/usr/bin/env python3
"""
Build Posts Index

Scans the posts directory and generates:
  - blog/posts/index.json   — metadata index used by the frontend loader
  - blog/p/<n>.html         — short-link redirect stubs (stable numbering)
  - rss.xml                 — RSS 2.0 feed (links to canonical post URLs)
  - blog/sitemap.xml        — sitemap for the blog index + every post
  - blog/index.html         — injects the real first page of posts between
                              POSTS:BEGIN/POSTS:END markers so crawlers see
                              genuine links instead of placeholder cards

Canonical post URL: https://bitroot.org/blog/<slug>/ (static pages built by
build_post_pages.py).
"""

import html as html_mod
import json
import math
import re
import shutil
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, ElementTree, indent

import frontmatter

POSTS_DIR = Path("blog/posts")
INDEX_FILE = POSTS_DIR / "index.json"
RSS_FILE = Path("rss.xml")
SHORT_LINKS_DIR = Path("blog/p")
BLOG_PAGES_DIR = Path("blog/page")
BLOG_SITEMAP_FILE = Path("blog/sitemap.xml")
BLOG_INDEX_HTML = Path("blog/index.html")

PER_PAGE = 9

SITE_URL = "https://bitroot.org"
BLOG_URL = f"{SITE_URL}/blog"
RSS_URL = f"{SITE_URL}/rss.xml"

POSTS_BEGIN = "<!-- POSTS:BEGIN — generated by build_index.py, do not edit by hand -->"
POSTS_END = "<!-- POSTS:END -->"

# Curated sections for the /blog index (Metaview-style rails). Auto-generated
# tags are a noisy long tail, so posts are bucketed by keyword on canonicalised
# tags (substring) and title (keywords of 5+ chars only, to avoid false hits).
# A post can sit in several categories. Keys are stable — they appear in
# /blog/?c=<key> links and in posts/index.json.
CATEGORIES = [
    ("models", "AI Models", [
        "claude", "openai", "gpt", "gemini", "fable", "opus", "sonnet", "llm",
        "anthropic", "deepseek", "kimi", "qwen", "grok", "mistral", "model",
    ]),
    ("agents", "Agents & Dev Tools", [
        "agent", "claudecode", "cursor", "coding", "cli", "mcp", "developer",
        "devtool", "api", "sdk", "github", "automation", "codex", "vscode", "terminal",
    ]),
    ("founders", "Founders & Business", [
        "founder", "startup", "pricing", "saas", "funding", "india", "business",
        "acquisition", "valuation", "revenue", "marketing", "economics",
    ]),
    ("opensource", "Open Source", ["opensource"]),
    ("design", "Design & Media", [
        "design", "figma", "video", "image", "animation", "uiux", "font", "color",
        "3d", "audio", "voice", "music", "creative",
    ]),
    ("engineering", "Engineering", [
        "postgres", "linux", "kernel", "rust", "typescript", "database", "debug",
        "compiler", "gpu", "cuda", "inference", "hardware", "browser", "security",
        "webassembly", "wasm", "microkernel", "ebpf", "lean", "simulat",
    ]),
]
CATEGORY_LABELS = {key: label for key, label, _ in CATEGORIES}
RAIL_SIZE = 8


def canon(s):
    return re.sub(r"[^a-z0-9]", "", str(s or "").lower())


def categorize(post):
    tags = [canon(t) for t in post.get("tags") or []]
    title = canon(post.get("title"))
    out = []
    for key, _, keywords in CATEGORIES:
        if any(kw in t for t in tags for kw in keywords) or any(
            kw in title for kw in keywords if len(kw) >= 5
        ):
            out.append(key)
    return out


def esc(s):
    return html_mod.escape(str(s or ""), quote=True)


def collapse_ws(s):
    return re.sub(r"\s+", " ", str(s or "")).strip()


def clamp(s, limit=160):
    s = collapse_ws(s)
    if len(s) <= limit:
        return s
    cut = s[: limit - 1]
    if " " in cut:
        cut = cut[: cut.rindex(" ")]
    return cut.rstrip(" ,;:.") + "…"


def post_url(slug):
    return f"{BLOG_URL}/{slug}/"


def absolute_image(image):
    """Absolute URL for a post image. Self-hosted images are stored as
    paths relative to /blog/ (e.g. 'media/foo.jpg')."""
    image = str(image or "")
    if not image or image.startswith(("http://", "https://")):
        return image
    if image.startswith("/"):
        return f"{SITE_URL}{image}"
    return f"{BLOG_URL}/{image}"


def get_post_metadata(filepath):
    """Extract metadata from a post file."""
    try:
        post = frontmatter.load(filepath)

        # Get image, skip deprecated unsplash source URLs
        image = post.metadata.get("image", "")
        if image and "source.unsplash.com" in image:
            image = ""  # Let frontend use tag-based fallback

        word_count = len(post.content.split())

        metadata = {
            "filename": filepath.name,
            "slug": filepath.stem,
            "url": f"/blog/{filepath.stem}/",
            "title": collapse_ws(post.metadata.get("title", "Untitled")),
            "date": str(post.metadata.get("date", "")),
            "published_at": post.metadata.get("published_at", ""),
            "tags": post.metadata.get("tags", []),
            "excerpt": collapse_ws(post.metadata.get("excerpt", "")),
            "image": image,
            "sources": post.metadata.get("sources", []),
            "readTime": f"{max(1, math.ceil(word_count / 200))} min",
        }
        metadata["categories"] = categorize(metadata)

        # Add video if present
        if post.metadata.get("video"):
            metadata["video"] = post.metadata.get("video")

        # Add media gallery if present
        if post.metadata.get("media"):
            metadata["media"] = post.metadata.get("media")

        return metadata
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None


def assign_short_ids(posts):
    """Stable short IDs: 1 = oldest post, ascending by (date, slug).

    New posts always get NEW numbers appended at the end, so published
    short links never re-point to a different article. (The legacy scheme
    numbered 1 = newest and renumbered everything on every build.)
    """
    ascending = sorted(posts, key=lambda p: (p.get("date", "") or "0000-00-00", p["slug"]))
    for i, post in enumerate(ascending, start=1):
        post["shortId"] = i


def build_short_links(posts):
    """Generate short-link redirect stubs at blog/p/<n>.html.

    Each stub carries the post's OG/Twitter meta (social scrapers read the
    stub itself), a canonical pointing at the post's clean URL, and an
    instant meta-refresh redirect (closest thing to a 301 on GitHub Pages).
    """
    SHORT_LINKS_DIR.mkdir(parents=True, exist_ok=True)
    expected = set()

    for post in posts:
        slug = post["slug"]
        title = post.get("title", "Untitled")
        excerpt = clamp(post.get("excerpt") or "Read this article on the Bitroot newslogger.")
        image = absolute_image(post.get("image")) or f"{SITE_URL}/images/newslogger-og.jpg"
        canonical = post_url(slug)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={canonical}">
<link rel="canonical" href="{canonical}">
<title>{esc(title)} | Bitroot Newslogger</title>
<meta property="og:type" content="article">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(excerpt)}">
<meta property="og:image" content="{esc(image)}">
<meta property="og:url" content="{canonical}">
<meta property="og:site_name" content="Bitroot">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(excerpt)}">
<meta name="twitter:image" content="{esc(image)}">
</head>
<body>
<p>Redirecting&hellip; <a href="{canonical}">Click here</a> if not redirected.</p>
</body>
</html>
"""
        filename = f"{post['shortId']}.html"
        expected.add(filename)
        (SHORT_LINKS_DIR / filename).write_text(html, encoding="utf-8")

    # Drop stubs for posts that no longer exist (never renumber live ones).
    for stale in SHORT_LINKS_DIR.glob("*.html"):
        if stale.name not in expected:
            stale.unlink()

    print(f"Generated {len(posts)} short link pages in {SHORT_LINKS_DIR}/")


def card_image(image):
    """Absolute, root-relative src for a card image. Self-hosted images are
    stored relative to /blog/ ('media/foo.jpg'); those must resolve the same
    from /blog/ and from a deeper /blog/page/<n>/ list page."""
    image = str(image or "")
    if not image:
        return "/blog/media/placeholder-blog.png"
    if image.startswith(("http://", "https://", "/")):
        return image
    return f"/blog/{image}"


ARROW_SVG = (
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" '
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
    '<path d="M7 17 17 7"/><path d="M8 7h9v9"/></svg>'
)


def card_label(post):
    cats = post.get("categories") or []
    if cats:
        return CATEGORY_LABELS.get(cats[0], cats[0])
    return (post.get("tags") or ["General"])[0]


def render_card(post, size="md", eager=False, indent=12):
    """One newslogger card. Mirror of posts-loader.js renderCard() so the JS
    filter view looks identical to the static sections crawlers see.
    size: "lg" (featured lead, with excerpt), "md" (grid/rail), "sm" (featured side)."""
    image = card_image(post.get("image"))
    slug = esc(post["slug"])
    # Alt text = the post title: the card image is the post's cover art.
    alt = esc(post.get("title") or "")
    loading = "eager" if eager else "lazy"
    fetchprio = ' fetchpriority="high"' if eager and size == "lg" else ""
    excerpt = ""
    if size == "lg":
        excerpt = f'\n    <p class="nl-card-excerpt">{esc(clamp(post.get("excerpt", ""), 200))}</p>'
    meta = f'{esc(fmt_card_date(post))} &middot; {esc(post.get("readTime", "5 min"))} read'
    pad = " " * indent
    html = f"""<a class="nl-card nl-card--{size}" data-post-slug="{slug}" href="{esc(post['url'])}">
    <div class="nl-card-media"><img src="{esc(image)}" alt="{alt}" loading="{loading}"{fetchprio} decoding="async" onerror="this.onerror=null;this.src=window.bitrootPixelPlaceholder?window.bitrootPixelPlaceholder('{slug}'):'/blog/media/placeholder-blog.png'"></div>
    <div class="nl-card-head">
        <h3 class="nl-card-title">{esc(post['title'])}</h3>
        <span class="nl-card-arrow">{ARROW_SVG}</span>
    </div>{excerpt}
    <div class="nl-card-meta"><span class="nl-card-cat">{esc(card_label(post))}</span><span>{meta}</span></div>
</a>"""
    return "\n".join(pad + line for line in html.split("\n"))


def fmt_card_date(post):
    pub = post.get("published_at") or post.get("date")
    try:
        dt = datetime.fromisoformat(str(pub))
        return f"{dt.day} {dt.strftime('%b')} {dt.year}"
    except (ValueError, TypeError):
        return str(post.get("date", ""))


def fmt_short_date(date_str):
    try:
        dt = datetime.fromisoformat(str(date_str))
        return f"{dt.strftime('%b')} {dt.day}"
    except (ValueError, TypeError):
        return str(date_str or "")


def fmt_display_date(post):
    pub = post.get("published_at")
    if pub:
        try:
            dt = datetime.fromisoformat(str(pub))
            hour12 = dt.hour % 12 or 12
            ampm = "AM" if dt.hour < 12 else "PM"
            return f"{dt.strftime('%B')} {dt.day}, {dt.year}, {hour12}:{dt.minute:02d} {ampm}"
        except (ValueError, TypeError):
            pass
    try:
        dt = datetime.fromisoformat(str(post.get("date", "")))
        return f"{dt.strftime('%b')} {dt.day}, {dt.year}"
    except (ValueError, TypeError):
        return str(post.get("date", ""))


def pagination_nav(current, total_pages):
    """Crawlable prev/next pagination markup. Page 1 lives at /blog/, the rest
    at /blog/page/<n>/. posts-loader.js swaps this for its SPA controls on
    load; crawlers and no-JS visitors follow the real <a href> links."""

    def href(n):
        return f"{BLOG_URL}/" if n <= 1 else f"/blog/page/{n}/"

    prev_svg = (
        '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6">'
        "</polyline></svg>"
    )
    next_svg = (
        '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6">'
        "</polyline></svg>"
    )

    if current <= 1:
        prev_el = (
            '<span class="pagination-btn prev" aria-disabled="true">'
            f"{prev_svg}<span>Prev</span></span>"
        )
    else:
        prev_el = (
            f'<a class="pagination-btn prev" href="{href(current - 1)}" '
            f'aria-label="Previous page">{prev_svg}<span>Prev</span></a>'
        )

    if current >= total_pages:
        next_el = (
            '<span class="pagination-btn next" aria-disabled="true">'
            f"<span>Next</span>{next_svg}</span>"
        )
    else:
        next_el = (
            f'<a class="pagination-btn next" href="{href(current + 1)}" '
            f'aria-label="Next page"><span>Next</span>{next_svg}</a>'
        )

    return f"""            <nav class="pagination" aria-label="Newslogger pagination">
                {prev_el}
                <span class="pagination-info">
                    Page <strong>{current}</strong> of <strong>{total_pages}</strong>
                </span>
                {next_el}
            </nav>"""


def all_posts_section(page_posts, current, total_pages, heading):
    cards = "\n".join(render_card(p, indent=16) for p in page_posts)
    return f"""        <section class="nl-section" aria-labelledby="nl-all-title">
            <div class="nl-section-head">
                <h2 class="nl-h2" id="nl-all-title">{heading}</h2>
            </div>
            <div class="nl-grid">
{cards}
            </div>
            <div class="pagination-container">
{pagination_nav(current, total_pages)}
            </div>
        </section>"""


SUBSCRIBE_HTML = """        <section class="nl-subscribe" aria-labelledby="nl-sub-title">
            <div class="nl-subscribe-copy">
                <h2 class="nl-subscribe-title" id="nl-sub-title">The newslogger, <em>in your inbox.</em></h2>
                <p>One short email when we publish. AI and founder tactics, no fluff, no spam.</p>
            </div>
            <form class="nl-form" data-nl-form data-nl-location="blog_index">
                <input type="email" name="email" required autocomplete="email" placeholder="you@company.com" aria-label="Email address">
                <button type="submit">Subscribe</button>
                <p class="nl-status" data-nl-status role="status" aria-live="polite"></p>
            </form>
        </section>"""


def inject_index_posts(posts, per_page=PER_PAGE):
    """Render the /blog home (Featured, subscribe band, one rail per category,
    and page 1 of All posts + a crawlable archive) between the POSTS markers."""
    if not BLOG_INDEX_HTML.exists():
        print(f"WARNING: {BLOG_INDEX_HTML} not found — skipping index injection")
        return

    html = BLOG_INDEX_HTML.read_text(encoding="utf-8")
    if POSTS_BEGIN not in html or POSTS_END not in html:
        print("WARNING: POSTS markers not found in blog/index.html — skipping injection")
        return

    total_pages = max(1, math.ceil(len(posts) / per_page))

    # Featured: newest post large, the next two stacked beside it.
    lead, side = posts[:1], posts[1:3]
    featured = ""
    if lead:
        side_cards = "\n".join(render_card(p, size="sm", eager=True, indent=20) for p in side)
        featured = f"""        <section class="nl-section nl-section--featured" aria-labelledby="nl-featured-title">
            <div class="nl-section-head">
                <h2 class="nl-h2" id="nl-featured-title">Featured</h2>
            </div>
            <div class="nl-featured">
{render_card(lead[0], size="lg", eager=True, indent=16)}
                <div class="nl-featured-side">
{side_cards}
                </div>
            </div>
        </section>"""

    rails = []
    for key, label, _ in CATEGORIES:
        items = [p for p in posts if key in (p.get("categories") or [])][:RAIL_SIZE]
        if len(items) < 3:
            continue
        cards = "\n".join(render_card(p, indent=20) for p in items)
        rails.append(f"""        <section class="nl-section nl-rail-section" data-cat="{key}" aria-labelledby="nl-rail-{key}">
            <div class="nl-section-head">
                <h2 class="nl-h2" id="nl-rail-{key}">{esc(label)}</h2>
                <div class="nl-rail-tools">
                    <button class="nl-rail-btn" type="button" data-rail-dir="-1" aria-label="Scroll {esc(label)} left" disabled><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg></button>
                    <button class="nl-rail-btn" type="button" data-rail-dir="1" aria-label="Scroll {esc(label)} right"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></button>
                    <a class="nl-viewall" href="/blog/?c={key}" data-cat="{key}">View all {ARROW_SVG}</a>
                </div>
            </div>
            <div class="nl-rail">
{cards}
            </div>
        </section>""")

    # Crawlable archive: every post beyond page 1 as a plain link list, in a
    # collapsed <details> so it doesn't read as a wall of text.
    archive_links = "\n".join(
        f'                <li><a href="{esc(p["url"])}">{esc(p["title"])}</a> <span class="archive-date">{esc(fmt_short_date(p.get("date", "")))}</span></li>'
        for p in posts[per_page:]
    )
    archive_html = ""
    if archive_links:
        archive_html = f"""
        <details class="post-archive" aria-label="All posts">
            <summary class="archive-title">Archive · all {len(posts)} posts</summary>
            <ul class="archive-list">
{archive_links}
            </ul>
        </details>"""

    body = "\n".join(
        [featured, SUBSCRIBE_HTML, *rails,
         all_posts_section(posts[:per_page], 1, total_pages, "All posts")]
    )
    generated = f"""{POSTS_BEGIN}
        <div id="nl-home">
{body}{archive_html}
        </div>
        {POSTS_END}"""

    pattern = re.compile(re.escape(POSTS_BEGIN) + r".*?" + re.escape(POSTS_END), re.S)
    html = pattern.sub(lambda _: generated, html)
    BLOG_INDEX_HTML.write_text(html, encoding="utf-8")
    print(f"Injected featured + {len(rails)} rails + {min(per_page, len(posts))} posts into {BLOG_INDEX_HTML}")


def build_pagination_pages(posts, per_page=PER_PAGE):
    """Generate crawlable /blog/page/<n>/ list pages for n = 2..N.

    Each page is a clone of the just-built blog/index.html shell with that
    page's nine cards and real prev/next <a href> links swapped in, so every
    post is reachable by a plain crawlable link even with JS disabled. Page 1
    stays at /blog/. Pages self-canonicalise and carry rel=prev/next; they are
    left indexable (per Google's post-rel=prev/next guidance) and listed in the
    blog sitemap.
    """
    if not BLOG_INDEX_HTML.exists():
        print(f"WARNING: {BLOG_INDEX_HTML} not found — skipping pagination pages")
        return

    shell = BLOG_INDEX_HTML.read_text(encoding="utf-8")
    if POSTS_BEGIN not in shell or POSTS_END not in shell:
        print("WARNING: POSTS markers not found — skipping pagination pages")
        return

    total_pages = max(1, math.ceil(len(posts) / per_page))
    BLOG_PAGES_DIR.mkdir(parents=True, exist_ok=True)

    # Drop stale page dirs (post count shrank, or a leftover page/1).
    keep = {str(n) for n in range(2, total_pages + 1)}
    for d in BLOG_PAGES_DIR.iterdir():
        if d.is_dir() and d.name not in keep:
            shutil.rmtree(d)

    block_re = re.compile(
        re.escape(POSTS_BEGIN) + r".*?" + re.escape(POSTS_END), re.S
    )

    for n in range(2, total_pages + 1):
        start = (n - 1) * per_page
        heading = f'All posts <span class="nl-h2-sub">Page {n} of {total_pages}</span>'
        section = all_posts_section(posts[start:start + per_page], n, total_pages, heading)
        block = f"""{POSTS_BEGIN}
        <div id="nl-home">
{section}
            <p class="pagination-back"><a href="{BLOG_URL}/">&larr; Back to the newslogger</a></p>
        </div>
        {POSTS_END}"""
        html = block_re.sub(lambda _: block, shell)

        canonical = f"{BLOG_URL}/page/{n}/"
        prev_url = f"{BLOG_URL}/" if n == 2 else f"{BLOG_URL}/page/{n - 1}/"
        head_extra = f'<link rel="canonical" href="{canonical}">\n'
        head_extra += f'    <link rel="prev" href="{prev_url}">'
        if n < total_pages:
            head_extra += f'\n    <link rel="next" href="{BLOG_URL}/page/{n + 1}/">'

        html = html.replace(
            '<link rel="canonical" href="https://bitroot.org/blog/">', head_extra, 1
        )
        html = html.replace(
            "<title>AI News for Founders & Builders — Bitroot Newslogger</title>",
            f"<title>Newslogger — Page {n} of {total_pages} | Bitroot</title>",
            1,
        )
        html = html.replace(
            '<meta property="og:url" content="https://bitroot.org/blog/">',
            f'<meta property="og:url" content="{canonical}">',
            1,
        )
        # Relative asset refs in the shell break one directory level deeper.
        html = html.replace('href="css/blog.css"', 'href="/blog/css/blog.css"')
        html = html.replace('href="css/newslogger.css"', 'href="/blog/css/newslogger.css"')
        html = html.replace('src="js/newsletter.js"', 'src="/blog/js/newsletter.js"')
        html = html.replace(
            'src="js/pixel-placeholder.js"', 'src="/blog/js/pixel-placeholder.js"'
        )
        html = html.replace(
            'src="js/posts-loader.js"', 'src="/blog/js/posts-loader.js"'
        )

        out_dir = BLOG_PAGES_DIR / str(n)
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "index.html").write_text(html, encoding="utf-8")

    print(f"Generated {max(0, total_pages - 1)} pagination pages in {BLOG_PAGES_DIR}/")


def build_blog_sitemap(posts, per_page=PER_PAGE):
    """Sitemap for the blog: index page + /blog/page/<n>/ + every post URL."""
    urlset = Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")

    newest = posts[0].get("date", "") if posts else ""
    url = SubElement(urlset, "url")
    SubElement(url, "loc").text = f"{BLOG_URL}/"
    if newest:
        SubElement(url, "lastmod").text = newest
    SubElement(url, "priority").text = "0.8"

    total_pages = max(1, math.ceil(len(posts) / per_page))
    for n in range(2, total_pages + 1):
        url = SubElement(urlset, "url")
        SubElement(url, "loc").text = f"{BLOG_URL}/page/{n}/"
        if newest:
            SubElement(url, "lastmod").text = newest
        SubElement(url, "priority").text = "0.4"

    for post in posts:
        url = SubElement(urlset, "url")
        SubElement(url, "loc").text = post_url(post["slug"])
        lastmod = str(post.get("date", "")) or None
        pub = post.get("published_at")
        if pub:
            try:
                lastmod = datetime.fromisoformat(str(pub)).date().isoformat()
            except (ValueError, TypeError):
                pass
        if lastmod:
            SubElement(url, "lastmod").text = lastmod

    indent(urlset, space="  ")
    ElementTree(urlset).write(BLOG_SITEMAP_FILE, encoding="unicode", xml_declaration=True)
    print(f"Generated {BLOG_SITEMAP_FILE} with {len(posts) + total_pages} URLs")


def guess_mime(url):
    u = url.lower().split("?")[0]
    if u.endswith(".png"):
        return "image/png"
    if u.endswith(".webp"):
        return "image/webp"
    if u.endswith(".gif"):
        return "image/gif"
    return "image/jpeg"


def build_index():
    """Build the posts index."""
    if not POSTS_DIR.exists():
        print(f"Posts directory not found: {POSTS_DIR}")
        return

    posts = []

    # Find all markdown files
    for filepath in POSTS_DIR.glob("*.md"):
        if filepath.name == ".gitkeep":
            continue

        metadata = get_post_metadata(filepath)
        if metadata:
            posts.append(metadata)
            print(f"  Found: {filepath.name} - {metadata['title']}")

    # Sort posts by date descending (newest first), slug as deterministic
    # tiebreak for same-date posts (file mtimes are unstable in CI checkouts).
    posts.sort(key=lambda p: (p.get("date", "") or "0000-00-00", p["slug"]), reverse=True)

    # Extract sorted post files list
    post_files = [p["filename"] for p in posts]

    print(f"\n  Sorted {len(posts)} posts by date (newest first)")

    # Stable short IDs, then redirect stubs
    assign_short_ids(posts)
    build_short_links(posts)

    # Write index file
    index_data = {
        "generated": True,
        "count": len(posts),
        "posts": post_files,
        "metadata": posts,
    }

    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(index_data, f, indent=2)

    print(f"\nGenerated {INDEX_FILE} with {len(posts)} posts")

    # Generate RSS feed, blog sitemap, and crawlable index content
    build_rss(posts)
    build_blog_sitemap(posts)
    inject_index_posts(posts)
    # Must run after inject_index_posts — it clones the freshly-injected shell.
    build_pagination_pages(posts)


def build_rss(posts):
    """Generate an RSS 2.0 feed from the posts metadata."""
    rss = Element("rss", version="2.0")
    rss.set("xmlns:atom", "http://www.w3.org/2005/Atom")

    channel = SubElement(rss, "channel")
    SubElement(channel, "title").text = "Newslogger | Bitroot"
    SubElement(channel, "link").text = f"{BLOG_URL}/"
    SubElement(channel, "description").text = (
        "Thoughts, tutorials, and insights from the Bitroot team."
    )
    SubElement(channel, "language").text = "en"
    SubElement(channel, "lastBuildDate").text = format_datetime(
        datetime.now(timezone.utc)
    )

    atom_link = SubElement(channel, "atom:link")
    atom_link.set("href", RSS_URL)
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")

    for post in posts:
        item = SubElement(channel, "item")
        SubElement(item, "title").text = post["title"]

        # Canonical clean URL — stable forever, unlike the short-link IDs.
        canonical = post_url(post["slug"])
        SubElement(item, "link").text = canonical

        guid = SubElement(item, "guid")
        guid.set("isPermaLink", "true")
        guid.text = canonical

        # Description: excerpt + citation
        desc = post.get("excerpt", "")
        sources = post.get("sources", [])
        if sources:
            citation_lines = "".join(
                f'<li><a href="{s}">{s}</a></li>' for s in sources
            )
            desc += f"\n\n<p><strong>Source:</strong></p><ul>{citation_lines}</ul>"
        SubElement(item, "description").text = desc

        # pubDate from published_at or date
        pub_str = post.get("published_at") or post.get("date", "")
        if pub_str:
            try:
                dt = datetime.fromisoformat(str(pub_str))
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                SubElement(item, "pubDate").text = format_datetime(dt)
            except (ValueError, TypeError):
                pass

        # Categories from tags
        for tag in post.get("tags", []):
            SubElement(item, "category").text = tag

        # Image enclosure (self-hosted media/ paths become absolute URLs)
        image = absolute_image(post.get("image", ""))
        if image:
            enc = SubElement(item, "enclosure")
            enc.set("url", image)
            enc.set("type", guess_mime(image))
            enc.set("length", "0")

        # Source element (RSS native citation)
        if sources:
            src = SubElement(item, "source")
            src.set("url", sources[0])
            src.text = "Original Source"

    indent(rss, space="  ")
    tree = ElementTree(rss)
    tree.write(RSS_FILE, encoding="unicode", xml_declaration=True)
    print(f"Generated {RSS_FILE} with {len(posts)} items")


if __name__ == "__main__":
    print("Building posts index...")
    build_index()
