#!/usr/bin/env python3
"""
Build Posts Index

Scans the posts directory and generates:
  - blog/posts/index.json   — metadata index used by the frontend loader
  - blog/p/<n>.html         — short-link redirect stubs (stable numbering)
  - rss.xml                 — RSS 2.0 feed (links to canonical post URLs)
  - blog/sitemap.xml        — sitemap for the blog index + every post
  - blog/index.html         — injects the real first page of posts between
                              POSTS:BEGIN/POSTS:END markers so crawlers see
                              genuine links instead of placeholder cards

Canonical post URL: https://bitroot.org/blog/<slug>/ (static pages built by
build_post_pages.py).
"""

import html as html_mod
import json
import math
import re
from datetime import datetime, timezone
from email.utils import format_datetime
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, ElementTree, indent

import frontmatter

POSTS_DIR = Path("blog/posts")
INDEX_FILE = POSTS_DIR / "index.json"
RSS_FILE = Path("rss.xml")
SHORT_LINKS_DIR = Path("blog/p")
BLOG_SITEMAP_FILE = Path("blog/sitemap.xml")
BLOG_INDEX_HTML = Path("blog/index.html")

SITE_URL = "https://bitroot.org"
BLOG_URL = f"{SITE_URL}/blog"
RSS_URL = f"{SITE_URL}/rss.xml"

POSTS_BEGIN = "<!-- POSTS:BEGIN — generated by build_index.py, do not edit by hand -->"
POSTS_END = "<!-- POSTS:END -->"


def esc(s):
    return html_mod.escape(str(s or ""), quote=True)


def collapse_ws(s):
    return re.sub(r"\s+", " ", str(s or "")).strip()


def clamp(s, limit=160):
    s = collapse_ws(s)
    if len(s) <= limit:
        return s
    cut = s[: limit - 1]
    if " " in cut:
        cut = cut[: cut.rindex(" ")]
    return cut.rstrip(" ,;:.") + "…"


def post_url(slug):
    return f"{BLOG_URL}/{slug}/"


def get_post_metadata(filepath):
    """Extract metadata from a post file."""
    try:
        post = frontmatter.load(filepath)

        # Get image, skip deprecated unsplash source URLs
        image = post.metadata.get("image", "")
        if image and "source.unsplash.com" in image:
            image = ""  # Let frontend use tag-based fallback

        word_count = len(post.content.split())

        metadata = {
            "filename": filepath.name,
            "slug": filepath.stem,
            "url": f"/blog/{filepath.stem}/",
            "title": collapse_ws(post.metadata.get("title", "Untitled")),
            "date": str(post.metadata.get("date", "")),
            "published_at": post.metadata.get("published_at", ""),
            "tags": post.metadata.get("tags", []),
            "excerpt": collapse_ws(post.metadata.get("excerpt", "")),
            "image": image,
            "sources": post.metadata.get("sources", []),
            "readTime": f"{max(1, math.ceil(word_count / 200))} min",
        }

        # Add video if present
        if post.metadata.get("video"):
            metadata["video"] = post.metadata.get("video")

        # Add media gallery if present
        if post.metadata.get("media"):
            metadata["media"] = post.metadata.get("media")

        return metadata
    except Exception as e:
        print(f"Error reading {filepath}: {e}")
        return None


def assign_short_ids(posts):
    """Stable short IDs: 1 = oldest post, ascending by (date, slug).

    New posts always get NEW numbers appended at the end, so published
    short links never re-point to a different article. (The legacy scheme
    numbered 1 = newest and renumbered everything on every build.)
    """
    ascending = sorted(posts, key=lambda p: (p.get("date", "") or "0000-00-00", p["slug"]))
    for i, post in enumerate(ascending, start=1):
        post["shortId"] = i


def build_short_links(posts):
    """Generate short-link redirect stubs at blog/p/<n>.html.

    Each stub carries the post's OG/Twitter meta (social scrapers read the
    stub itself), a canonical pointing at the post's clean URL, and an
    instant meta-refresh redirect (closest thing to a 301 on GitHub Pages).
    """
    SHORT_LINKS_DIR.mkdir(parents=True, exist_ok=True)
    expected = set()

    for post in posts:
        slug = post["slug"]
        title = post.get("title", "Untitled")
        excerpt = clamp(post.get("excerpt") or "Read this article on the Bitroot newslogger.")
        image = post.get("image") or f"{SITE_URL}/images/newslogger-og.jpg"
        canonical = post_url(slug)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={canonical}">
<link rel="canonical" href="{canonical}">
<title>{esc(title)} | Bitroot Newslogger</title>
<meta property="og:type" content="article">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(excerpt)}">
<meta property="og:image" content="{esc(image)}">
<meta property="og:url" content="{canonical}">
<meta property="og:site_name" content="Bitroot Newslogger">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{esc(title)}">
<meta name="twitter:description" content="{esc(excerpt)}">
<meta name="twitter:image" content="{esc(image)}">
</head>
<body>
<p>Redirecting&hellip; <a href="{canonical}">Click here</a> if not redirected.</p>
</body>
</html>
"""
        filename = f"{post['shortId']}.html"
        expected.add(filename)
        (SHORT_LINKS_DIR / filename).write_text(html, encoding="utf-8")

    # Drop stubs for posts that no longer exist (never renumber live ones).
    for stale in SHORT_LINKS_DIR.glob("*.html"):
        if stale.name not in expected:
            stale.unlink()

    print(f"Generated {len(posts)} short link pages in {SHORT_LINKS_DIR}/")


def render_featured_card(post):
    """Mirror of posts-loader.js renderFeaturedPost() so the JS hydration
    swaps content without layout shift."""
    tag = (post.get("tags") or ["General"])[0]
    image = post.get("image") or "media/placeholder-blog.png"
    display_date = fmt_display_date(post)
    return f"""            <article class="featured-post" data-post-slug="{esc(post['slug'])}">
                <div class="featured-progress"><div class="featured-progress-bar"></div></div>
                <div class="post-image">
                    <img src="{esc(image)}" alt="{esc(post['title'])}" width="800" height="450" fetchpriority="high" decoding="async">
                </div>
                <div class="post-content">
                    <div class="post-meta">
                        <span class="post-tag">{esc(tag)}</span>
                        <span class="post-date">{esc(display_date)}</span>
                    </div>
                    <h2 class="post-title">{esc(post['title'])}</h2>
                    <p class="post-excerpt">{esc(clamp(post.get('excerpt', ''), 220))}</p>
                    <div class="post-footer">
                        <span class="read-time">{esc(post.get('readTime', '5 min'))} read</span>
                        <a href="{esc(post['url'])}" class="read-more">Read more &rarr;</a>
                    </div>
                </div>
            </article>"""


def render_list_item(post, active=False):
    """Mirror of posts-loader.js renderListItemWithState() — real anchors so
    every post link is crawlable and tappable."""
    tag = (post.get("tags") or ["General"])[0]
    short_date = fmt_short_date(post.get("date", ""))
    return f"""                <a class="list-item{' active' if active else ''}" data-post-slug="{esc(post['slug'])}" href="{esc(post['url'])}">
                    <span class="list-date">{esc(short_date)}</span>
                    <div class="list-content">
                        <span class="list-tag">{esc(tag)}</span>
                        <h3 class="list-title">{esc(post['title'])}</h3>
                        <span class="list-read-time">{esc(post.get('readTime', '5 min'))}</span>
                    </div>
                </a>"""


def fmt_short_date(date_str):
    try:
        dt = datetime.fromisoformat(str(date_str))
        return f"{dt.strftime('%b')} {dt.day}"
    except (ValueError, TypeError):
        return str(date_str or "")


def fmt_display_date(post):
    pub = post.get("published_at")
    if pub:
        try:
            dt = datetime.fromisoformat(str(pub))
            hour12 = dt.hour % 12 or 12
            ampm = "AM" if dt.hour < 12 else "PM"
            return f"{dt.strftime('%B')} {dt.day}, {dt.year}, {hour12}:{dt.minute:02d} {ampm}"
        except (ValueError, TypeError):
            pass
    try:
        dt = datetime.fromisoformat(str(post.get("date", "")))
        return f"{dt.strftime('%b')} {dt.day}, {dt.year}"
    except (ValueError, TypeError):
        return str(post.get("date", ""))


def inject_index_posts(posts, per_page=5):
    """Write the real first page of posts (plus a crawlable archive of every
    remaining post title) into blog/index.html between the POSTS markers."""
    if not BLOG_INDEX_HTML.exists():
        print(f"WARNING: {BLOG_INDEX_HTML} not found — skipping index injection")
        return

    html = BLOG_INDEX_HTML.read_text(encoding="utf-8")
    if POSTS_BEGIN not in html or POSTS_END not in html:
        print("WARNING: POSTS markers not found in blog/index.html — skipping injection")
        return

    page_posts = posts[:per_page]
    featured = page_posts[0]
    total_pages = max(1, math.ceil(len(posts) / per_page))

    list_items = "\n".join(
        render_list_item(p, active=(p["slug"] == featured["slug"])) for p in page_posts
    )
    # Crawlable archive: every post beyond page 1 as a plain link list. The
    # loader's pagination takes over for sighted users; this keeps discovery
    # and PageRank flow intact for crawlers (and works without JS).
    archive_links = "\n".join(
        f'                <li><a href="{esc(p["url"])}">{esc(p["title"])}</a> <span class="archive-date">{esc(fmt_short_date(p.get("date", "")))}</span></li>'
        for p in posts[per_page:]
    )
    archive_html = ""
    if archive_links:
        archive_html = f"""
        <section class="post-archive" aria-label="All posts">
            <h2 class="archive-title">All posts</h2>
            <ul class="archive-list">
{archive_links}
            </ul>
        </section>"""

    generated = f"""{POSTS_BEGIN}
        <div class="showcase-grid">
{render_featured_card(featured)}
            <aside class="post-list">
                <h2 class="list-header">Recent</h2>
{list_items}
            </aside>
        </div>
        <div class="pagination-container">
            <nav class="pagination" aria-label="Newslogger pagination">
                <button class="pagination-btn prev" disabled aria-label="Previous page">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <polyline points="15 18 9 12 15 6"></polyline>
                    </svg>
                    <span>Prev</span>
                </button>
                <span class="pagination-info">
                    Page <strong>1</strong> of <strong>{total_pages}</strong>
                </span>
                <button class="pagination-btn next" {'disabled ' if total_pages == 1 else ''}aria-label="Next page">
                    <span>Next</span>
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <polyline points="9 18 15 12 9 6"></polyline>
                    </svg>
                </button>
            </nav>
        </div>{archive_html}
        {POSTS_END}"""

    pattern = re.compile(re.escape(POSTS_BEGIN) + r".*?" + re.escape(POSTS_END), re.S)
    html = pattern.sub(lambda _: generated, html)
    BLOG_INDEX_HTML.write_text(html, encoding="utf-8")
    print(f"Injected {len(page_posts)} posts + {len(posts) - len(page_posts)} archive links into {BLOG_INDEX_HTML}")


def build_blog_sitemap(posts):
    """Sitemap for the blog: index page + every post's clean URL."""
    urlset = Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")

    newest = posts[0].get("date", "") if posts else ""
    url = SubElement(urlset, "url")
    SubElement(url, "loc").text = f"{BLOG_URL}/"
    if newest:
        SubElement(url, "lastmod").text = newest
    SubElement(url, "priority").text = "0.8"

    for post in posts:
        url = SubElement(urlset, "url")
        SubElement(url, "loc").text = post_url(post["slug"])
        lastmod = str(post.get("date", "")) or None
        pub = post.get("published_at")
        if pub:
            try:
                lastmod = datetime.fromisoformat(str(pub)).date().isoformat()
            except (ValueError, TypeError):
                pass
        if lastmod:
            SubElement(url, "lastmod").text = lastmod

    indent(urlset, space="  ")
    ElementTree(urlset).write(BLOG_SITEMAP_FILE, encoding="unicode", xml_declaration=True)
    print(f"Generated {BLOG_SITEMAP_FILE} with {len(posts) + 1} URLs")


def guess_mime(url):
    u = url.lower().split("?")[0]
    if u.endswith(".png"):
        return "image/png"
    if u.endswith(".webp"):
        return "image/webp"
    if u.endswith(".gif"):
        return "image/gif"
    return "image/jpeg"


def build_index():
    """Build the posts index."""
    if not POSTS_DIR.exists():
        print(f"Posts directory not found: {POSTS_DIR}")
        return

    posts = []

    # Find all markdown files
    for filepath in POSTS_DIR.glob("*.md"):
        if filepath.name == ".gitkeep":
            continue

        metadata = get_post_metadata(filepath)
        if metadata:
            posts.append(metadata)
            print(f"  Found: {filepath.name} - {metadata['title']}")

    # Sort posts by date descending (newest first), slug as deterministic
    # tiebreak for same-date posts (file mtimes are unstable in CI checkouts).
    posts.sort(key=lambda p: (p.get("date", "") or "0000-00-00", p["slug"]), reverse=True)

    # Extract sorted post files list
    post_files = [p["filename"] for p in posts]

    print(f"\n  Sorted {len(posts)} posts by date (newest first)")

    # Stable short IDs, then redirect stubs
    assign_short_ids(posts)
    build_short_links(posts)

    # Write index file
    index_data = {
        "generated": True,
        "count": len(posts),
        "posts": post_files,
        "metadata": posts,
    }

    with open(INDEX_FILE, "w", encoding="utf-8") as f:
        json.dump(index_data, f, indent=2)

    print(f"\nGenerated {INDEX_FILE} with {len(posts)} posts")

    # Generate RSS feed, blog sitemap, and crawlable index content
    build_rss(posts)
    build_blog_sitemap(posts)
    inject_index_posts(posts)


def build_rss(posts):
    """Generate an RSS 2.0 feed from the posts metadata."""
    rss = Element("rss", version="2.0")
    rss.set("xmlns:atom", "http://www.w3.org/2005/Atom")

    channel = SubElement(rss, "channel")
    SubElement(channel, "title").text = "Newslogger | Bitroot"
    SubElement(channel, "link").text = f"{BLOG_URL}/"
    SubElement(channel, "description").text = (
        "Thoughts, tutorials, and insights from the Bitroot team."
    )
    SubElement(channel, "language").text = "en"
    SubElement(channel, "lastBuildDate").text = format_datetime(
        datetime.now(timezone.utc)
    )

    atom_link = SubElement(channel, "atom:link")
    atom_link.set("href", RSS_URL)
    atom_link.set("rel", "self")
    atom_link.set("type", "application/rss+xml")

    for post in posts:
        item = SubElement(channel, "item")
        SubElement(item, "title").text = post["title"]

        # Canonical clean URL — stable forever, unlike the short-link IDs.
        canonical = post_url(post["slug"])
        SubElement(item, "link").text = canonical

        guid = SubElement(item, "guid")
        guid.set("isPermaLink", "true")
        guid.text = canonical

        # Description: excerpt + citation
        desc = post.get("excerpt", "")
        sources = post.get("sources", [])
        if sources:
            citation_lines = "".join(
                f'<li><a href="{s}">{s}</a></li>' for s in sources
            )
            desc += f"\n\n<p><strong>Source:</strong></p><ul>{citation_lines}</ul>"
        SubElement(item, "description").text = desc

        # pubDate from published_at or date
        pub_str = post.get("published_at") or post.get("date", "")
        if pub_str:
            try:
                dt = datetime.fromisoformat(str(pub_str))
                if dt.tzinfo is None:
                    dt = dt.replace(tzinfo=timezone.utc)
                SubElement(item, "pubDate").text = format_datetime(dt)
            except (ValueError, TypeError):
                pass

        # Categories from tags
        for tag in post.get("tags", []):
            SubElement(item, "category").text = tag

        # Image enclosure
        image = post.get("image", "")
        if image and image.startswith("http"):
            enc = SubElement(item, "enclosure")
            enc.set("url", image)
            enc.set("type", guess_mime(image))
            enc.set("length", "0")

        # Source element (RSS native citation)
        if sources:
            src = SubElement(item, "source")
            src.set("url", sources[0])
            src.text = "Original Source"

    indent(rss, space="  ")
    tree = ElementTree(rss)
    tree.write(RSS_FILE, encoding="unicode", xml_declaration=True)
    print(f"Generated {RSS_FILE} with {len(posts)} items")


if __name__ == "__main__":
    print("Building posts index...")
    build_index()
