#!/usr/bin/env bash
# Open ONE pull request per post generated by generate_post.py.
#
# generate_post.py writes, for each post, <OUT>/<slug>.md (the PR body) and
# <OUT>/<slug>.json (title, post file, media files). A separate PR per post means
# TeamLife's Blog Studio lists each draft on its own and a weak one can be closed
# without blocking the rest (a single batch PR only ever described the last post).
#
# Env: GITHUB_TOKEN, GITHUB_REPOSITORY, BASE_BRANCH, RUN_ID, TRIGGER (label text)
set -euo pipefail

OUT="${BLOG_AGENT_OUT:-.blog-agent-out}"
BASE="${BASE_BRANCH:-main}"
[ -d "$OUT" ] || { echo "No generated posts."; exit 0; }
shopt -s nullglob
manifests=("$OUT"/*.json)
[ ${#manifests[@]} -gt 0 ] || { echo "No generated posts."; exit 0; }

git config user.name "blog-agent[bot]"
git config user.email "actions@github.com"
git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git fetch -q origin "$BASE"
export GH_TOKEN="$GITHUB_TOKEN"

n=0
for manifest in "${manifests[@]}"; do
  n=$((n + 1))
  base="$(basename "$manifest" .json)"
  title="$(jq -r .title "$manifest")"
  file="$(jq -r .file "$manifest")"
  issue="$(jq -r .issue "$manifest")"
  branch="blog-post-${RUN_ID:-local}-${n}"

  # Each post starts from a clean copy of the base; the other posts' files stay
  # untracked in the working tree until their own turn.
  git checkout -q -B "$branch" "origin/$BASE"
  git add -- "$file"
  jq -r '.media[]' "$manifest" | while read -r m; do [ -n "$m" ] && git add -- "$m"; done

  if git diff --cached --quiet; then
    echo "Nothing to commit for $base — skipping."
    continue
  fi

  git commit -q -m "blog: Add post — ${title}"
  git push -q -f origin "$branch"

  body="$(cat "$OUT/$base.md")

---

### Review checklist
- [ ] Every claim is supported by the linked sources
- [ ] Sources are properly attributed
- [ ] Tone matches Bitroot style

> Index, short links, and RSS are rebuilt automatically after merge.

_Generated with [Blog Agent](/.github/workflows/blog-agent.yml) from issue #${issue}_"

  gh pr create --base "$BASE" --head "$branch" \
    --title "📝 ${title}" --body "$body" --label blog-post
  echo "Opened PR for: $title"
done
